# Canonical discriminant analysis

In [1]:
# Chargement des donnees
import pandas as pd
import numpy as np
from plydata import *
import os
os.chdir("d:/Bureau/PythonProject/packages/scientisttools/data/")

In [2]:
wine = pd.read_excel("wine_quality.xls",index_col=1)
display(wine >> head()) 

Obs.  Temperature  Soleil  Chaleur  Pluie   Qualite
Annee                                                     
1924      1         3064    1201       10    361     Moyen
1925      2         3000    1053       11    338  Mediocre
1926      3         3155    1133       19    393     Moyen
1927      4         3085     970        4    467  Mediocre
1928      5         3245    1258       36    294       Bon

In [3]:
from scientisttools.discriminant_analysis import CANDISC

In [4]:
my_cda = CANDISC(n_components=2,
                 target=["Qualite"],
                 row_labels=wine.index,
                 features_labels=["Temperature","Soleil","Chaleur","Pluie"],
                 parallelize=False)
my_cda.fit(wine)

CANDISC(features_labels=['Temperature', 'Soleil', 'Chaleur', 'Pluie'],
        n_components=2,
        row_labels=Int64Index([1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934,
            1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945,
            1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956,
            1957],
           dtype='int64', name='Annee'),
        target=['Qualite'])

In [5]:
my_cda.classes_

array(['Bon', 'Mediocre', 'Moyen'], dtype=object)

In [6]:
my_cda.summary_information_

value
Total Sample Size      34
Variables               4
Classes                 3
DF Total               33
DF Within Classes      31
DF Between Classes      2

In [7]:
my_cda.class_level_information_

n(k)      p(k)
Qualite                 
Mediocre    12  0.352941
Bon         11  0.323529
Moyen       11  0.323529

In [8]:
my_cda.squared_mdist_

Bon   Mediocre     Moyen
Bon        0.000000  17.652729  4.519311
Mediocre  17.652729   0.000000  5.492267
Moyen      4.519311   5.492267  0.000000

In [9]:
my_cda.univariate_test_statistis_

Std. Dev.  R-squared  Rsq/(1-Rsq)  F-statistic  \
Temperature  141.184334   0.638605     1.767052    27.389310   
Soleil       126.622972   0.617857     1.616822    25.060741   
Chaleur       10.016564   0.497312     0.989305    15.334220   
Pluie         91.401608   0.352537     0.544491     8.439607   

             Prob (F-statistic)  
Temperature        1.408416e-07  
Soleil             3.345802e-07  
Chaleur            2.344932e-05  
Pluie              1.185298e-03

In [10]:
anova = my_cda.anova_
anova

sum_sq    df        mean_sq          F  \
Temperature C(Qualite)  420067.408200   2.0  210033.704100  27.389310   
            Residual    237722.121212  31.0    7668.455523        NaN   
Soleil      C(Qualite)  326909.069964   2.0  163454.534982  25.060741   
            Residual    202192.371212  31.0    6522.334555        NaN   
Chaleur     C(Qualite)    1646.569964   2.0     823.284982  15.334220   
            Residual      1664.371212  31.0      53.689394        NaN   
Pluie       C(Qualite)   97191.170232   2.0   48595.585116   8.439607   
            Residual    178499.212121  31.0    5758.039101        NaN   

                              PR(>F)    eta_sq  omega_sq  
Temperature C(Qualite)  1.408416e-07  0.638605  0.608198  
            Residual             NaN       NaN       NaN  
Soleil      C(Qualite)  3.345802e-07  0.617857  0.585979  
            Residual             NaN       NaN       NaN  
Chaleur     C(Qualite)  2.344932e-05  0.497312  0.457462  
            Residual             NaN       NaN       NaN  
Pluie       C(Qualite)  1.185298e-03  0.352537  0.304408  
            Residual             NaN       NaN       NaN

In [11]:
my_cda.correlation_ratio_

Sum. Intra   Sum. Inter  correlation ratio  F-stats  pvalue
Temperature  237722.1212  420067.4082             0.6386  27.3893  0.0000
Soleil       202192.3712  326909.0700             0.6179  25.0607  0.0000
Chaleur        1664.3712    1646.5700             0.4973  15.3342  0.0000
Pluie        178499.2121   97191.1702             0.3525   8.4396  0.0012

In [12]:
print(my_cda.manova_)

                 Multivariate linear model
                                                            
------------------------------------------------------------
        Qualite         Value  Num DF  Den DF F Value Pr > F
------------------------------------------------------------
          Wilks' lambda 0.2053 8.0000 56.0000  8.4505 0.0000
         Pillai's trace 0.8880 8.0000 58.0000  5.7896 0.0000
 Hotelling-Lawley trace 3.4174 8.0000 37.7500 11.7280 0.0000
    Roy's greatest root 3.2789 4.0000 29.0000 23.7717 0.0000



In [13]:
tukey = my_cda.tukey_
print(tukey["Temperature"])

     Multiple Comparison of Means - Tukey HSD, FWER=0.05     
 group1   group2   meandiff p-adj    lower     upper   reject
-------------------------------------------------------------
     Bon Mediocre -269.0303    0.0 -358.9958 -179.0648   True
     Bon    Moyen -165.4545 0.0003  -257.355  -73.5541   True
Mediocre    Moyen  103.5758 0.0213   13.6103  193.5412   True
-------------------------------------------------------------


In [14]:
bonf_test = my_cda.bonferroni_correction_
print(bonf_test["Temperature"])

Test Multiple Comparison ttest_ind 
FWER=0.05 method=bonf
alphacSidak=0.02, alphacBonf=0.017
 group1   group2    stat   pval  pval_corr reject
-------------------------------------------------
     Bon Mediocre  7.9611    0.0       0.0   True
     Bon    Moyen  4.0363 0.0006    0.0019   True
Mediocre    Moyen -2.9072 0.0084    0.0253   True
-------------------------------------------------


In [15]:
sidak = my_cda.sidak_
print(sidak["Temperature"])

Test Multiple Comparison ttest_ind 
FWER=0.05 method=sidak
alphacSidak=0.02, alphacBonf=0.017
 group1   group2    stat   pval  pval_corr reject
-------------------------------------------------
     Bon Mediocre  7.9611    0.0       0.0   True
     Bon    Moyen  4.0363 0.0006    0.0019   True
Mediocre    Moyen -2.9072 0.0084    0.0251   True
-------------------------------------------------


In [16]:
my_cda.tcov_

Temperature        Soleil      Chaleur        Pluie
Temperature  19346.750865  12360.302768  1187.420415 -5130.448097
Soleil       12360.302768  15561.807093   795.792388 -5317.760381
Chaleur       1187.420415    795.792388    97.380623  -356.451557
Pluie        -5130.448097  -5317.760381  -356.451557  8108.540657

In [17]:
my_cda.tcorr_

LD1       LD2
Temperature -0.900589 -0.374779
Soleil      -0.896744  0.116190
Chaleur     -0.770513 -0.590030
Pluie        0.662815 -0.361294

In [18]:
my_cda.gcov_

Temperature       Soleil     Chaleur         Pluie
Qualite                                                                  
Bon      Temperature   8474.454545  3390.845455  585.281818  -2709.100000
         Soleil        3390.845455  6449.054545  163.118182  -1336.100000
         Chaleur        585.281818   163.118182   77.472727   -306.100000
         Pluie        -2709.100000 -1336.100000 -306.100000   2734.600000
Mediocre Temperature   4807.878788 -1003.606061  233.515152    227.060606
         Soleil       -1003.606061  7813.356061  157.416667    -59.787879
         Chaleur        233.515152   157.416667   39.719697    -25.575758
         Pluie          227.060606   -59.787879  -25.575758  10992.606061
Moyen    Temperature  10009.090909  3541.590909  587.945455   3793.063636
         Soleil        3541.590909  5175.490909  188.245455    912.063636
         Chaleur        587.945455   188.245455   45.272727    226.281818
         Pluie         3793.063636   912.063636  226.281818   3023.454545

In [19]:
my_cda.wcov_

Temperature       Soleil     Chaleur        Pluie
Temperature  6991.827094  1714.255793  420.615865   392.273619
Soleil       1714.255793  5946.834447  154.271168  -144.059715
Chaleur       420.615865   154.271168   48.952094   -31.750446
Pluie         392.273619  -144.059715  -31.750446  5249.976827

In [20]:
my_cda.wcorr_

LD1       LD2
Temperature -0.724221 -0.584256
Soleil      -0.701280  0.176148
Chaleur     -0.525372 -0.779910
Pluie        0.398218 -0.420797

In [21]:
my_cda.bcorr_

LD1       LD2
Temperature -0.986651 -0.211244
Soleil      -0.998654  0.002625
Chaleur     -0.957391 -0.335599
Pluie        0.976576 -0.166812

In [22]:
my_cda.eig_.T

array([[  3.27886049,   3.14028647,  95.94508632,  95.94508632],
       [  0.13857402,          nan,   4.05491368, 100.        ]])

In [23]:
my_cda.intercept_

array([32.87628192, -2.16527944])

In [24]:
my_cda.coef_

array([[-8.56604551e-03,  4.62505890e-05],
       [-6.77386899e-03,  5.32929330e-03],
       [ 2.70544919e-02, -1.27636164e-01],
       [ 5.86566500e-03, -6.17455623e-03]])

In [25]:
from scientisttools.extractfactor import get_candisc
row_coord = get_candisc(my_cda)
row_coord["coord"].head()

LD1       LD2
Annee                    
1924   0.882552  0.871537
1925   2.325456  0.094220
1926   0.994856 -0.832957
1927   2.726862 -0.247244
1928  -0.743596 -1.721167

In [26]:
my_cda.global_performance_

Stat      Value       p-value
0     Wilks' Lambda   0.205263           NaN
1  Bartlett -- C(8)  46.712169  1.739815e-07
2    Rao -- F(8,56)   8.450507  1.890358e-07

In [27]:
my_cda.likelihood_test_

statistic  DDL num.  DDL den.          Pr>F
0   8.450507       8.0      56.0  1.890358e-07
1   1.339549       3.0      29.0  2.807850e-01

In [28]:
transform = my_cda.transform(wine.drop(columns=["Qualite","Obs."]))
transform.iloc[:5,:]

LD1       LD2
Annee                    
1924   0.882552  0.871537
1925   2.325456  0.094220
1926   0.994856 -0.832957
1927   2.726862 -0.247244
1928  -0.743596 -1.721167

In [29]:
Xtest = pd.DataFrame(np.array([3000,1100,20,300]).reshape(1,4),index=['1958'],
                     columns = my_cda.features_labels_)
Xtest

Temperature  Soleil  Chaleur  Pluie
1958         3000    1100       20    300

In [30]:
my_cda.transform(Xtest)

LD1       LD2
1958  2.027679 -0.569395

In [31]:
X = wine[my_cda.features_labels_]

In [32]:
predict_proba = my_cda.predict_proba(X)
predict_proba.head().round(4)

Bon  Mediocre   Moyen
Annee                          
1924   0.0067    0.3446  0.6487
1925   0.0000    0.9588  0.0411
1926   0.0092    0.6980  0.2927
1927   0.0000    0.9865  0.0135
1928   0.6417    0.0313  0.3270

In [33]:
my_cda.decision_function(Xtest)

Bon  Mediocre     Moyen
1958 -7.56466  1.114437 -1.859627

In [34]:
predict_proba = my_cda.predict_proba(X)
predict_proba.head()

Bon  Mediocre     Moyen
Annee                              
1924   0.006695  0.344613  0.648692
1925   0.000045  0.958846  0.041109
1926   0.009222  0.698039  0.292739
1927   0.000009  0.986519  0.013472
1928   0.641715  0.031256  0.327029

In [35]:
my_cda.predict(Xtest)

predict
1958  Mediocre

In [36]:
my_cda.score(X,wine["Qualite"])

0.7941176470588235

In [37]:
from scientisttools.extractfactor import get_eigenvalue,summaryCANDISC,get_candisc_coef
eig = get_eigenvalue(my_cda)
eig

eigenvalue  difference  proportion  cumulative
LD1    3.278860    3.140286   95.945086   95.945086
LD2    0.138574         NaN    4.054914  100.000000

In [38]:
coef = get_candisc_coef(my_cda,choice="absolute")
coef

LD1       LD2
Temperature  -0.008566  0.000046
Soleil       -0.006774  0.005329
Chaleur       0.027054 -0.127636
Pluie         0.005866 -0.006175
Intercept    32.876282 -2.165279

In [39]:
coef = get_candisc_coef(my_cda,choice="score")
coef

Bon   Mediocre     Moyen
Temperature   0.018164  -0.017821  0.001277
Soleil        0.012925  -0.015263  0.003726
Chaleur      -0.022716   0.084484 -0.069449
Pluie        -0.010768   0.013562 -0.004026
Intercept   -72.590473  65.609287 -7.191833

In [40]:
summaryCANDISC(my_cda,to_markdown=True)

                     Canonical Discriminant Analysis - Results                     


Summary Information
|       |   Total Sample Size |   Variables |   Classes |   DF Total |   DF Within Classes |   DF Between Classes |
|:------|--------------------:|------------:|----------:|-----------:|--------------------:|---------------------:|
| value |                  34 |           4 |         3 |         33 |                  31 |                    2 |

Class Level information
|               |   n(k) |     p(k) |
|:--------------|-------:|---------:|
| ('Mediocre',) |     12 | 0.352941 |
| ('Bon',)      |     11 | 0.323529 |
| ('Moyen',)    |     11 | 0.323529 |

Importance of components
|                         |    LD1 |     LD2 |
|:------------------------|-------:|--------:|
| Variance                |  3.279 |   0.139 |
| Difference              |  3.14  | nan     |
| % of var.               | 95.945 |   4.055 |
| Cumulative of % of var. | 95.945 | 100     |

Group means:
| Qualite